### ISSUE TITLE
Trouble rendering ComboBox with MXHX

### ISSUE THREAD

**Issue by Aszusz** [mxhx-dev/mxhx-feathersui#1]
I'm trying to render ComboBox with DataProvider and the default ItemRenderer:
```
<f:ComboBox>
  <f:dataProvider>
    <f:ArrayCollection>
      <mx:Array type="String">
        <mx:String>Excellent</mx:String>
        <mx:String>Good</mx:String>
        <mx:String>Satisfactory</mx:String>
        <mx:String>Needs Improvement</mx:String>
      </mx:Array>
    </f:ArrayCollection>
  </f:dataProvider>
</f:ComboBox>
```
After clicking the ComboBox arrow, the item list does not render correctly:
![ComboBox](https://github.com/mxhx-dev/mxhx-feathersui/assets/7197014/cdec5987-73a1-4e85-aa92-39f495a4ca64)

Is this supported yet?
I'm using html target and building with Moonshine IDE.

**Comment by joshtynjala** [comment]
I actually just added support to Feathers UI for plain strings in data providers last month. Previously, you were expected to use some kind of object (such as `<mx:Struct text="Excellent"/>` in MXHX) with an `itemToText` function. To be able to use strings, you'll need the latest Feathers UI source code from GitHub, as it has not yet been released to Haxelib. If you're already using it from GitHub, and it's still not working, there's a good chance that you may need to update from an older commit.

feathersui/feathersui-openfl@fb4fa5bf1539c2c6fea7bf99fda1d7079f1fd716

I can confirm that your MXHX code is working on my machine with the latest Feathers UI (and no changes required to mxhx-feathersui).

**Comment by Aszusz** [comment]
Thank you, I was using cached Feathers UI by mistake. Works with the latest commit.
